spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:orchestrator_db}
    username: ${POSTGRES_USER:orchestrator}
    password: ${POSTGRES_PASSWORD:orchestrator}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
